-- AlterTable
ALTER TABLE "students" ADD COLUMN     "backlogSubjects" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "course" TEXT,
ADD COLUMN     "entranceCategory" TEXT,
ADD COLUMN     "entranceExam" TEXT,
ADD COLUMN     "entranceRank" TEXT,
ADD COLUMN     "semester1Cgpa" DOUBLE PRECISION,
ADD COLUMN     "semester2Cgpa" DOUBLE PRECISION,
ADD COLUMN     "semester3Cgpa" DOUBLE PRECISION,
ADD COLUMN     "semester4Cgpa" DOUBLE PRECISION,
ADD COLUMN     "semester5Cgpa" DOUBLE PRECISION,
ADD COLUMN     "semester6Cgpa" DOUBLE PRECISION,
ADD COLUMN     "semester7Cgpa" DOUBLE PRECISION,
ADD COLUMN     "semester8Cgpa" DOUBLE PRECISION,
ADD COLUMN     "tenthBoard" TEXT,
ADD COLUMN     "tenthSchoolName" TEXT,
ADD COLUMN     "tenthSubjects" TEXT,
ADD COLUMN     "tenthYearOfPassing" TEXT,
ADD COLUMN     "twelfthBoard" TEXT,
ADD COLUMN     "twelfthSchoolName" TEXT,
ADD COLUMN     "twelfthSubjects" TEXT,
ADD COLUMN     "twelfthYearOfPassing" TEXT,
ADD COLUMN     "yearOfGraduation" TEXT;
